version: '3'
services:
  server:
    build: .
    environment:
      DB_HOST: "db"
    ports:
      - 3000:3000
      - 8000:8000
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: blogdatabase
    ports:
      - 27017:27017

  upsub:
    image: upsub/dispatcher
    ports:
      - 4400:4400
